### PR TITLE
Fixed error with empty strings strings

### PR DESCRIPTION
**Pull request by woverton**

### CODE REVIEW

**Comment by se0kjun** [comment]
:+1: thank you!

**Comment by woverton** [comment]
If you could do a npm release that would be awesome :smile:

**Comment by se0kjun** [comment]
:ok_hand: release just a moment ago!
try to **npm update**

**Comment by woverton** [comment]
:anguished: might have introduced a bug :cry: 

This fix stops errors for strings that do not contain any ansi characters, but doesn't substring the actual string :/

it should be 

```
if(!ansiResult){
    return str.substring(start, end);
}
```

instead of 

```
if(!ansiResult){
    return ""
}
```

I shall make a pull request, sorry!

**Pull request merged**
